### PR TITLE
About us page

### PR DESCRIPTION
**Pull request by tomheller**
First draft, PR open for preview and review.

### CODE REVIEW

**Comment by metmajer** [comment]
@tomheller, thanks for this cool update! Here are a couple of things to discuss:

### Main Hero

- The lines in the hero background image on the main page are blurred, although we're using an `.svg` file. The blurring comes from the use of `background-size: cover;`, which is shown by disabling the attribute in my latest Chrome browser. The hero section should look sharp. Can you think of an alternative? I assume that if we set the size of the SVG to match the current resolution, we could achieve this sharpness. Thoughts?

### About Us Page

- The avatar in the circle looks very blurry. Looking at the [image URL](https://d33wubrfki0l68.cloudfront.net/796983e11834049911a5374e58d34df4253304ca/c3527/martin-etmajer.jpg) it seems like the image doesn't have the best quality. If this is what comes out of the Sketch template, I'll send you a higher quality image via email. What is the preferred image size?
- The hero on this page is also of very low quality. I'll send you the highest resolution via email as well. Let's not down-scale it. 1 MB for this image shouldn't be too big.
- Please use the background color value which we have in the "What People Say" section on the main page on the left the right side surrounding the "inner page" on the About Us page.
- Please allow more room between the social icons (see the Sketch template). Can we also rearrange them in the following order? 1) LinkedIn 2) GitHub 3) Twitter 4) Speaker Deck 5) SlideShare. Looking at the template, I also feel that they should be a little bigger in size. Thanks for having a second look!
- The `hr` line below the header should align with the lower end of the avatar image.
- The social icons should be top-aligned with the text body. Please sure that, if you move the icons up a little, the space between avatar image, social icons and text doesn't look crammed. The sketch template  shows the optimal.
- I've tried to change the dimensions of the `tags`, but the text doesn't remain vertically aligned. I am not sure why though. Also, the browser shows that `word-break: nowrap;` can't be applied.
- The page looks great on a mobile resolution, but if you could please have another look at the social icons? Since they're aligned on a horizontal line, the height of the images becomes more important than their width. Also, there's a problem with the burger menu.
- The page should also include the "What People Say" section, as shown in the Sketch template.

**Comment by tomheller** [comment]
@metmajer 
Main Hero
* Fixed the positioning on the background. This should keep the svg lines sharp. As there was the idea of animating this and creating theses circles with algorithms, this would keep them sharp on all screen sizes. 

About us page:
* Avatar image updated. The originals were just fine, I have just over-optimized them to keep load times low. 
* Same as the avatar image, I have updated both images, they are now crisp, but add loadtimes
* Background color around the about-us has been fixed
* Social Icons have been reorded, given more space and increased in size. 
* HR is now aligned properly
* Social icons are now aligned at the top of the text
* I've fixed the problem with the nowrap property. What did you try to do with changing the dimensions?
* Fixed the hamburger menu
* Added the what people say section (Whoops, I should have scrolled down on the page in sketch)

Thank you for the feedback, this really helps. For me it's really tough to see all these alignments, that you have pointed out in the feedback, within the sketch file, because I can only guess if a certain alignment was just by coincidence or intended to be there. 

I hope that I have fit everything of you feedback into these changes. Let me know if there is anything else I can fix there.

**Comment by metmajer** [comment]
Awesome work, @tomheller! Can we please have these final adaptations on the about page?

- Change the `padding-top` attribute of the `testimonials` from `5.5rem` to `2.5rem`
- Please double-check the left and right margins of the text block with the Sketch file
- The text block and the tag buttons should be left-aligned
- I've increased the height of the buttons, but the texts don't align vertically even when I set `vertical-align: middle` (I'll have to change the button dimensions later on)
- If you take another look at the Sketch file, the white page should have a slight drop shadow

Thanks!

**Comment by tomheller** [comment]
I'll have a look at the feedback some time during the weekend.
If you increase the height of the buttons, you will have to increase the line height to the same value to have the vertical-align work. At which height did you want them to be?

**Comment by metmajer** [comment]
Ah, I had only played around inside the Chrome Developer Tools and had missed the existence of the `line-height` attribute. Thanks for that!

**Pull request merged**
